import { NutritionalSupplementsInterface } from './nutritional-supplements.interface'

export const nutritionalSupplements: NutritionalSupplementsInterface[] = [
  { number: 'Е319', status: 'HALAL', namerus: 'Третичный бутилгидрохинон', namelat: 'Tert-butylhydroquinone' },
  { number: 'E100', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E101', status: 'HALAL', namerus: 'Рибофлавин (витамин B2)', namelat: 'Riboflavin (vitamin B2)' },
  { number: 'E102', status: 'HALAL', namerus: 'Тартразин', namelat: 'Tartrazine' },
  { number: 'E103', status: 'HALAL', namerus: 'Алканет', namelat: 'Chrysoine resorcinol' },
  { number: 'E104', status: 'HALAL', namerus: 'Желтый хинолиновый', namelat: 'Quinoline Yellow' },
  { number: 'E105', status: 'HALAL', namerus: 'Желтый прочный AB', namelat: 'Fast Yellow AB' },
  { number: 'E106', status: 'HALAL', namerus: 'Рибофлавин-5 &#039;-фосфат натрия, натриевая соль витамина В2', namelat: 'Riboflavin-5-Phospate sodium salt, Vitamin B2 phospate sodium' },
  { number: 'E107', status: 'HALAL', namerus: 'Желтый 2G', namelat: 'Yellow 2G' },
  { number: 'E110', status: 'HALAL', namerus: 'Желтый "Солнечный закат"', namelat: 'Sunset Yellow FCF (Orange Yellow S)' },
  { number: 'E1103', status: 'HALAL', namerus: 'Фермент инвертаза', namelat: 'Invertase enzyme' },
  { number: 'E1105', status: 'HALAL', namerus: 'Фермент лизоцим', namelat: 'Lysozyme enzyme' },
  { number: 'E120', status: 'HARAM', namerus: 'Кошениль/карминовая кислота', namelat: 'Cochineal/carminic acid' },
  { number: 'E1200', status: 'HALAL', namerus: 'Полидекстроза', namelat: 'Polydextrose' },
  { number: 'E1201', status: 'HALAL', namerus: 'Поливинилпирролидон', namelat: 'Polyvinylpyrrolidone' },
  { number: 'E122', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E123', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E124', status: 'HALAL', namerus: 'Пунцовый 4R', namelat: 'Ponceau 4r/cochineal red a' },
  { number: 'E125', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E126', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E127', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E128', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E129', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E131', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E132', status: 'HALAL', namerus: 'Краситель', namelat: 'Colouring' },
  { number: 'E140', status: 'HALAL', namerus: 'Хлорофилл', namelat: 'Chlorophyll' },
  { number: 'E1400', status: 'HALAL', namerus: 'Декстрин', namelat: 'Dextrin' },
  { number: 'E1401', status: 'HALAL', namerus: 'Крахмал, обработанный кислотой', namelat: 'Acid-treated starch' },
  { number: 'E1404', status: 'HALAL', namerus: 'Крахмал окисленный', namelat: 'Oxidized starch' },
  { number: 'E141', status: 'HALAL', namerus: 'Медные комплексы хлорофиллов', namelat: 'Copper complexes of chlorophylls' },
  { number: 'E1410', status: 'HALAL', namerus: 'Загуститель, стабилизатор', namelat: 'Thickener, stabilizer' },
  { number: 'E1412', status: 'HALAL', namerus: 'Дикрахмалфосфат', namelat: 'Distarch phosphate' },
  { number: 'E1413', status: 'HALAL', namerus: 'Фосфатированный дикрахмалфосфат', namelat: 'Phosphated distarch phosphate' },
  { number: 'E142', status: 'HALAL', namerus: 'Зеленый S', namelat: 'Green S/acid brilliant green bs' },
  { number: 'E1420', status: 'HALAL', namerus: 'Ацетилированный крахмал', namelat: 'Acetylated starch' },
  { number: 'E1422', status: 'HALAL', namerus: 'Ацетилированный дикрахмалфосфат', namelat: 'Acetylated distarch phosphate' },
  { number: 'E1442', status: 'HALAL', namerus: 'Гидроксипропил дикрахмалфосфат', namelat: 'Hydroxy propyl distarch phosphate' },
  { number: 'E1450', status: 'HALAL', namerus: 'Эфир крахмала и натриевой соли октенилянтарной кислоты', namelat: 'Starch sodium octenyl succinate' },
  { number: 'E1451', status: 'HALAL', namerus: 'Ацетилированный окисленный крахмал', namelat: 'Acetylated oxidised starch' },
  { number: 'E150 (A-D)', status: 'HALAL', namerus: 'Сахарный колер с химическими добавками', namelat: 'Caramel colour/with chemicals' },
  { number: 'E1505', status: 'HALAL', namerus: 'Триэтилцитрат', namelat: 'Triethyl citrate' },
  { number: 'E151', status: 'HALAL', namerus: 'Черный блестящий BN', namelat: 'Black pn/brillliant black pn' },
  { number: 'E1518', status: 'HALAL', namerus: 'Триацетин', namelat: 'Glyceryl triacetate, triacetin' },
  { number: 'E1520', status: 'HALAL', namerus: 'Пропиленгликоль', namelat: 'Propylene glycol' },
  { number: 'E153', status: 'HALAL', namerus: 'Уголь растительный', namelat: 'Carbon black/vegetable carbon' },
  { number: 'E154', status: 'HALAL', namerus: 'Коричневый FK', namelat: 'Brown fk' },
  { number: 'E155', status: 'HALAL', namerus: 'Коричневый HT', namelat: 'Brown ht' },
  { number: 'E160A', status: 'HALAL', namerus: 'Альфа-, бета-, гамма-каротины', namelat: 'Alpha-carotene, Beta-carotene, Gamma-carotene' },
  { number: 'E160B', status: 'HALAL', namerus: 'Аннато, биксин, норбиксин', namelat: 'Annatto, bixin, norbixin' },
  { number: 'E160C', status: 'HALAL', namerus: 'Капсантин, капсорубин', namelat: 'Capsanthin, capsorubin' },
  { number: 'E160D', status: 'HALAL', namerus: 'Ликопин', namelat: 'Lycopene' },
  { number: 'E160E', status: 'HALAL', namerus: 'Каротиновый альдегид', namelat: 'Beta-apo-8 &#039;-carotenal' },
  { number: 'E160F', status: 'HALAL', namerus: 'Этиловый эфир каротиновой кислоты', namelat: 'Ethyl ester of beta-apo-8 &#039;-carotenic acid' },
  { number: 'E161A', status: 'HALAL', namerus: 'Флавоксантин', namelat: 'Flavoxanthin' },
  { number: 'E161B', status: 'HALAL', namerus: 'Лютеин', namelat: 'Lutein' },
  { number: 'E161C', status: 'HALAL', namerus: 'Криптоксантин', namelat: 'Cryptoxanthin' },
  { number: 'E161D', status: 'HALAL', namerus: 'Рубиксантин', namelat: 'Rubixanthin' },
  { number: 'E161E', status: 'HALAL', namerus: 'Виолоксантин', namelat: 'Violaxanthin' },
  { number: 'E161F', status: 'HALAL', namerus: 'Родоксантин', namelat: 'Rhodoxanthin' },
  { number: 'E161G', status: 'HALAL', namerus: 'Кантаксантин', namelat: 'Canthaxanthin' },
  { number: 'E162', status: 'HALAL', namerus: 'Свекольный красный, бетанин', namelat: 'Beetroot Red, Betanin' },
  { number: 'E163', status: 'HALAL', namerus: 'Антоцианы', namelat: 'Anthocyanins' },
  { number: 'E170', status: 'HALAL', namerus: 'Карбонаты кальция', namelat: 'Calcium carbonate, Chalk' },
  { number: 'E171', status: 'HALAL', namerus: 'Диоксид титана', namelat: 'Titanium dioxide' },
  { number: 'E172', status: 'HALAL', namerus: 'Оксиды и гидроксиды железа', namelat: 'Iron oxides and iron hydroxides' },
  { number: 'E173', status: 'HALAL', namerus: 'Алюминий', namelat: 'Aluminium' },
  { number: 'E174', status: 'HALAL', namerus: 'Серебро', namelat: 'Silver' },
  { number: 'E175', status: 'HALAL', namerus: 'Золото', namelat: 'Gold' },
  { number: 'E180', status: 'HALAL', namerus: 'Рубиновый литол ВК', namelat: 'Pigment Rubine, Lithol Rubine BK' },
  { number: 'Е200', status: 'HALAL', namerus: 'Сорбиновая кислота', namelat: 'Sorbic acid' },
  { number: 'Е201', status: 'HALAL', namerus: 'Сорбат натрия', namelat: 'Sodium sorbate' },
  { number: 'Е202', status: 'HALAL', namerus: 'Сорбат калия', namelat: 'Potassium sorbate' },
  { number: 'Е203', status: 'HALAL', namerus: 'Сорбат кальция', namelat: 'Calcium sorbate' },
  { number: 'Е210', status: 'HALAL', namerus: 'Бензойная кислота', namelat: 'Benzoic acid' },
  { number: 'Е211', status: 'HALAL', namerus: 'Бензоат натрия', namelat: 'Sodium benzoate' },
  { number: 'Е212', status: 'HALAL', namerus: 'Бензоат калия', namelat: 'Potassium benzoate' },
  { number: 'Е213', status: 'HALAL', namerus: 'Бензоат кальция', namelat: 'Calcium benzoate' },
  { number: 'Е214', status: 'HALAL', namerus: 'Пара-гидроксибензойной кислоты этиловый эфир', namelat: 'Ethyl 4- hydroxybenzoate' },
  { number: 'Е215', status: 'HALAL', namerus: 'Пара-гидроксибензойной кислоты этилового эфира натриевая соль', namelat: 'Sodium ethyl 4-hydroxybenzoate' },
  { number: 'Е216', status: 'HALAL', namerus: 'Пара-оксибензойной кислоты пропиловый эфир', namelat: 'propyl 4-hydroxybenzoate' },
  { number: 'Е217', status: 'HALAL', namerus: 'Пара-оксибензойной кислоты пропилового эфира натриевая соль', namelat: 'Sodium propyl 4-hydroxybenzoate' },
  { number: 'Е218', status: 'HALAL', namerus: 'Пара-гидроксибензойной кислоты метиловый эфир', namelat: 'methyl 4-hydroxybenzoate' },
  { number: 'Е219', status: 'HALAL', namerus: 'Пара-гидроксибензойной кислоты метилового эфира натриевая соль', namelat: 'Sodium methyl4- hydroxybenzoate' },
  { number: 'Е220', status: 'HALAL', namerus: 'Диоксид серы', namelat: 'Sulphur dioxide' },
  { number: 'Е221', status: 'HALAL', namerus: 'Сульфит натрия', namelat: 'Sodium sulphite' },
  { number: 'Е222', status: 'HALAL', namerus: 'Гидросульфит натрия', namelat: 'sodium hydrogen sulphite' },
  { number: 'Е223', status: 'HALAL', namerus: 'Пиросульфит натрия', namelat: 'Sodium metabisulphite' },
  { number: 'Е224', status: 'HALAL', namerus: 'Пиросульфит калия', namelat: 'Potassium metabisulphite' },
  { number: 'Е225', status: 'HALAL', namerus: 'Сульфит калия', namelat: 'Potassium sulphite' },
  { number: 'Е226', status: 'HALAL', namerus: 'Сульфит кальция', namelat: 'Calcium sulphite' },
  { number: 'Е227', status: 'HALAL', namerus: 'Гидросульфит кальция', namelat: 'Calcium hydrogen sulphite' },
  { number: 'Е228', status: 'HALAL', namerus: 'Гидросульфит калия', namelat: 'Potassium hydrogen sulphite' },
  { number: 'Е230', status: 'HALAL', namerus: 'Бифенил, дифенил', namelat: 'Biphenyl, diphenyl' },
  { number: 'Е231', status: 'HALAL', namerus: 'Ортофенилфенол', namelat: 'Orthophenyl phenol' },
  { number: 'Е232', status: 'HALAL', namerus: 'Ортофенилфенол натрия', namelat: 'Sodium orthophenyl phenol' },
  { number: 'Е233', status: 'HALAL', namerus: 'Тиабендазол', namelat: 'Thiabendazole' },
  { number: 'Е234', status: 'HALAL', namerus: 'Низин', namelat: 'Nisin' },
  { number: 'Е235', status: 'HALAL', namerus: 'Натамицин', namelat: 'Natamycin' },
  { number: 'E239', status: 'HALAL', namerus: 'Гексаметилентетрамин', namelat: 'Hexamine' },
  { number: 'E242', status: 'HALAL', namerus: 'Диметилдикарбонат', namelat: 'Dimethyl dicarbonate' },
  { number: 'E249', status: 'HALAL', namerus: 'Нитрит калия', namelat: 'Potassium nitrite' },
  { number: 'E250', status: 'HALAL', namerus: 'Нитрит натрия', namelat: 'Sodium nitrite' },
  { number: 'E251', status: 'HALAL', namerus: 'Нитрат натрия', namelat: 'Sodium nitrate' },
  { number: 'E252', status: 'HALAL', namerus: 'Нитрат калия', namelat: 'Potassium nitrate' },
  { number: 'E260', status: 'HALAL', namerus: 'Уксусная кислота', namelat: 'Acetic acid' },
  { number: 'E261', status: 'HALAL', namerus: 'Ацетат калия', namelat: 'Potassium acetate' },
  { number: 'E262', status: 'HALAL', namerus: 'Ацетат натрия', namelat: 'Sodium acetates' },
  { number: 'E263', status: 'HALAL', namerus: 'Ацетат кальция', namelat: 'Calcium acetate' },
  { number: 'E264', status: 'HALAL', namerus: 'Ацетат аммония', namelat: 'Ammonium acetate' },
  { number: 'E270', status: 'HALAL', namerus: 'Молочная кислота', namelat: 'Lactic acid' },
  { number: 'E280', status: 'HALAL', namerus: 'Пропионовая кислота', namelat: 'Propionic acid' },
  { number: 'E281', status: 'HALAL', namerus: 'Пропионат натрия', namelat: 'Sodium propionate' },
  { number: 'E282', status: 'HALAL', namerus: 'Пропионат кальция', namelat: 'Calcium propionate' },
  { number: 'E283', status: 'HALAL', namerus: 'Пропионат калия', namelat: 'Potassium propionate' },
  { number: 'E284', status: 'HALAL', namerus: 'Борная кислота', namelat: 'Boric acid' },
  { number: 'E285', status: 'HALAL', namerus: 'Тетраборат натрия (боракс)', namelat: 'Sodium tetraborate, borax' },
  { number: 'E290', status: 'HALAL', namerus: 'Диоксид углерода', namelat: 'Carbon dioxide' },
  { number: 'E296', status: 'HALAL', namerus: 'Яблочная кислота', namelat: 'Malic acid' },
  { number: 'E297', status: 'HALAL', namerus: 'Фумаровая кислота', namelat: 'Fumaric acid' },
  { number: 'E300', status: 'HALAL', namerus: 'Аскорбиновая кислота (Витамин С)', namelat: 'Ascorbic acid (Vitamin C)' },
  { number: 'E301', status: 'HALAL', namerus: 'Аскорбат натрия', namelat: 'Sodium ascorbate' },
  { number: 'E302', status: 'HALAL', namerus: 'Аскорбат кальция', namelat: 'Calcium ascorbate' },
  { number: 'E304', status: 'HALAL', namerus: 'Аскорбилпальмитат', namelat: 'Ascorbyl palmitate' },
  { number: 'E306', status: 'HALAL', namerus: 'Антиоксидант - витамин Е', namelat: 'Antioxidants - vitamin E' },
  { number: 'E307', status: 'HALAL', namerus: 'Синтетический Альфа-токоферол', namelat: 'Alpha-Tocopherol (synthetic)' },
  { number: 'E308', status: 'HALAL', namerus: 'Синтетический Гамма-токоферол', namelat: 'Gamma-Tocopherol (synthetic)' },
  { number: 'E309', status: 'HALAL', namerus: 'Синтетический Дельта - токоферол', namelat: 'Delta-Tocopherol (synthetic)' },
  { number: 'E310', status: 'HALAL', namerus: 'Пропилгаллат', namelat: 'Propyl gallate' },
  { number: 'E311', status: 'HALAL', namerus: 'Октилгаллат', namelat: 'Octyl gallate' },
  { number: 'E312', status: 'HALAL', namerus: 'Додецилгаллат', namelat: 'Dodecyl gallate' },
  { number: 'E315', status: 'HALAL', namerus: 'Эриторбовая кислота', namelat: 'Erythorbic acid' },
  { number: 'E316', status: 'HALAL', namerus: 'Эриторбат натрия', namelat: 'Sodium erythorbate' },
  { number: 'E320', status: 'HALAL', namerus: 'Бутилгидроксианизол', namelat: 'Butylated hydroxyanisole (BHA)' },
  { number: 'E321', status: 'HALAL', namerus: 'Бутилгидрокситолуол', namelat: 'Butylated hydroxytoluene (BHT)' },
  { number: 'E322', status: 'HALAL', namerus: 'Лецитин', namelat: 'Lecithin' },
  { number: 'E325', status: 'HALAL', namerus: 'Лактат натрия', namelat: 'Sodium lactate' },
  { number: 'E326', status: 'HALAL', namerus: 'Лактат калия', namelat: 'Potassium lactate' },
  { number: 'E327', status: 'HALAL', namerus: 'Лактат кальция', namelat: 'Calcium lactate' },
  { number: 'E330', status: 'HALAL', namerus: 'Лимонная кислота', namelat: 'Citric acid' },
  { number: 'E331', status: 'HALAL', namerus: 'Цитраты натрия', namelat: 'Sodium citrates' },
  { number: 'E332', status: 'HALAL', namerus: 'Цитраты калия', namelat: 'Potassium citrates' },
  { number: 'E333', status: 'HALAL', namerus: 'Цитраты кальция', namelat: 'Calcium citrates' },
  { number: 'E334', status: 'HALAL', namerus: 'Винная кислота', namelat: 'Tartaric acid' },
  { number: 'E335', status: 'HALAL', namerus: 'Тартраты натрия', namelat: 'Sodium tartrates' },
  { number: 'E336', status: 'HALAL', namerus: 'Тартраты калия', namelat: 'Potassium tartrates (cream of)' },
  { number: 'E337', status: 'HALAL', namerus: 'Тартраты калия-натрия', namelat: 'Potassium sodium tartrate' },
  { number: 'E338', status: 'HALAL', namerus: 'Ортофосфорная кислота', namelat: 'Orthophosphoric acid' },
  { number: 'E339', status: 'HALAL', namerus: 'Фосфаты натрия', namelat: 'Sodium phosphates' },
  { number: 'E340', status: 'HALAL', namerus: 'Фосфаты калия', namelat: 'Potassium phosphates' },
  { number: 'E341', status: 'HALAL', namerus: 'Фосфаты кальция', namelat: 'Calcium phosphates' },
  { number: 'E343', status: 'HALAL', namerus: 'Фосфаты магния', namelat: 'Magnesium phosphates' },
  { number: 'E350', status: 'HALAL', namerus: 'Малат натрия', namelat: 'Sodium malate' },
  { number: 'E351', status: 'HALAL', namerus: 'Малат калия', namelat: 'Potassium malate' },
  { number: 'E352', status: 'HALAL', namerus: 'Малат кальция', namelat: 'Calcium malate' },
  { number: 'E353', status: 'HALAL', namerus: 'Мета-винная кислота', namelat: 'Metatartaric acid' },
  { number: 'E354', status: 'HARAM', namerus: 'Тартрат кальция', namelat: 'Calcium tartrate' },
  { number: 'E355', status: 'HALAL', namerus: 'Адипиновая кислота', namelat: 'Adipic acid' },
  { number: 'E356', status: 'HALAL', namerus: 'Адипат натрия', namelat: 'Sodium adipate' },
  { number: 'E357', status: 'HALAL', namerus: 'Адипат калия', namelat: 'Potassium adipate' },
  { number: 'E363', status: 'HALAL', namerus: 'Янтарная кислота', namelat: 'Succinic acid' },
  { number: 'E370', status: 'HALAL', namerus: 'Гептонолактон', namelat: '1,4-Heptonolactone' },
  { number: 'E375', status: 'HALAL', namerus: 'Никотиновая кислота', namelat: 'Nicotinic acid' },
  { number: 'E380', status: 'HALAL', namerus: 'Цитрат аммония', namelat: 'Triammonium citrate' },
  { number: 'E381', status: 'HALAL', namerus: 'Железо-аммонийный цитрат', namelat: 'Ammonium ferric citrate' },
  { number: 'E385', status: 'HALAL', namerus: 'Этилендиаминтетраацетат кальция-натрия', namelat: 'Calcium disodium EDTA' },
  { number: 'E400', status: 'HALAL', namerus: 'Альгиновая кислота', namelat: 'Alginic acid' },
  { number: 'E401', status: 'HALAL', namerus: 'Альгинат натрия', namelat: 'Sodium alginate' },
  { number: 'E402', status: 'HALAL', namerus: 'Альгинат калия', namelat: 'Potassium alginate' },
  { number: 'E403', status: 'HALAL', namerus: 'Альгинат аммония', namelat: 'Ammonium alginate' },
  { number: 'E404', status: 'HALAL', namerus: 'Альгинат кальция', namelat: 'Calcium alginate' },
  { number: 'E405', status: 'HALAL', namerus: 'Пропан-1,2-диол альгинат', namelat: 'Propane-1,2-diol alginate' },
  { number: 'E406', status: 'HALAL', namerus: 'Агар', namelat: 'Agar' },
  { number: 'E407', status: 'HALAL', namerus: 'Каррагенан', namelat: 'Carrageenan' },
  { number: 'E410', status: 'HALAL', namerus: 'Камедь рожкового дерева', namelat: 'Locust bean gum (Carob gum)' },
  { number: 'E412', status: 'HALAL', namerus: 'Гуаровая камедь', namelat: 'Guar gum' },
  { number: 'E413', status: 'HALAL', namerus: 'Трагакант', namelat: 'Трагакант' },
  { number: 'E414', status: 'HALAL', namerus: 'Гуммиарабик', namelat: 'Acacia gum (gum arabic)' },
  { number: 'E415', status: 'HALAL', namerus: 'Ксантановая камедь', namelat: 'Xanthan gum' },
  { number: 'E416', status: 'HALAL', namerus: 'Карайи камедь', namelat: 'Karaya gum' },
  { number: 'E417', status: 'HALAL', namerus: 'Тары камедь', namelat: 'Tara gum' },
  { number: 'E418', status: 'HALAL', namerus: 'Геллановая камедь', namelat: 'Gellan gum' },
  { number: 'E420', status: 'HALAL', namerus: 'Сорбит', namelat: 'Sorbitol' },
  { number: 'E421', status: 'HALAL', namerus: 'Маннит', namelat: 'Mannitol' },
  { number: 'E422', status: 'MUSHBOOH', namerus: 'Глицерин', namelat: 'Glycerol' },
  { number: 'E425', status: 'HALAL', namerus: 'Коньяк смола', namelat: 'Konjac' },
  { number: 'E430', status: 'HALAL', namerus: 'Полиоксиэтилена (8) стеарат', namelat: 'Polyoxyethene (8) stearate' },
  { number: 'E431', status: 'HALAL', namerus: 'Полиоксиэтилен (40) стеарат', namelat: 'Polyoxyethene (40) stearate' },
  { number: 'E432', status: 'HALAL', namerus: 'Полиоксиэтиленсорбитан (20) монолаурат/полисорбат 20', namelat: 'Polyoxyethene (20) sorbitan monolaurate (polysorbate 20)' },
  { number: 'E433', status: 'HALAL', namerus: 'Полиоксиэтиленсорбитан (20) моноолеат/полисорбат 80', namelat: 'Polyoxyethene (20) sorbitan monooleate (polysorbate 80)' },
  { number: 'E434', status: 'HALAL', namerus: 'Полиоксиэтиленсорбитан (20) монопальмитат/полисорбат 40', namelat: 'Polyoxyethene (20) sorbitan monopalmitate (polysorbate 40)' },
  { number: 'E435', status: 'HALAL', namerus: 'Полиоксиэтилен сорбитан (20) моностеарат/полисорбат 60', namelat: 'Polyoxyethene (20) sorbitan monostearate (polysorbate 60)' },
  { number: 'E436', status: 'HALAL', namerus: 'Полиоксиэтиленсорбитан (20) тристеарат/полисорбат 65', namelat: 'Polyoxyethene (20) sorbitan tristearate (polysorbate 65)' },
  { number: 'E440A', status: 'HALAL', namerus: 'Пектин', namelat: 'Pectin' },
  { number: 'E440B', status: 'HALAL', namerus: 'Амидированный пектин', namelat: 'Amidated pectin' },
  { number: 'E441', status: 'MUSHBOOH', namerus: 'Желатин', namelat: 'Gelatin' },
  { number: 'E442', status: 'HALAL', namerus: 'Фосфатида аммонийные соли', namelat: 'Ammonium phosphatides' },
  { number: 'E444', status: 'HALAL', namerus: 'Сахарозы ацетат изобутират', namelat: 'Sucrose acetate isobutyrate' },
  { number: 'E445', status: 'MUSHBOOH', namerus: 'Эфиры глицерина и смоляных кислот', namelat: 'Glycerol esters of wood rosins' },
  { number: 'E450 A,B,C', status: 'HALAL', namerus: 'Фосфаты и полифосфаты натрия и калия', namelat: 'Sodium and potassium phosphates and polyphosphates' },
  { number: 'E451', status: 'HALAL', namerus: 'Трифосфаты', namelat: 'Triphosphates' },
  { number: 'E452', status: 'HALAL', namerus: 'Полифосфаты', namelat: 'Polyphosphates' },
  { number: 'E459', status: 'HALAL', namerus: 'Бета-циклодекстрин', namelat: 'Beta-cyclodextrin' },
  { number: 'E460', status: 'HALAL', namerus: 'Микрокристаллическая целлюлоза, целлюлоза в порошке', namelat: 'Microcrystalline cellulose/Powdered cellulose' },
  { number: 'E461', status: 'HALAL', namerus: 'Метилцеллюлоза', namelat: 'Methyl cellulose' },
  { number: 'E463', status: 'HALAL', namerus: 'Гидроксипропилцеллюлоза', namelat: 'Hydroxypropyl cellulose' },
  { number: 'E464', status: 'HALAL', namerus: 'Гидроксипропилметилцеллюлоза', namelat: 'hydroxypropyl methylcellulose' },
  { number: 'E465', status: 'HALAL', namerus: 'Этилметилцеллюлоза', namelat: 'Ethyl methyl cellulose' },
  { number: 'E466', status: 'HALAL', namerus: 'Карбоксиметилцеллюлоза', namelat: 'Carboxymethyl cellulose, Sodium carboxymethyl cellulose' },
  { number: 'E467', status: 'HALAL', namerus: 'Этилгидроксиэтилцеллюлоза', namelat: 'Ethyl hydroxyethyl cellulose' },
  { number: 'E468', status: 'HALAL', namerus: 'Карбоксиметилцеллюлозы натриевая соль трехмерная', namelat: 'Crosslinked sodium carboxymethyl cellulose' },
  { number: 'E469', status: 'HALAL', namerus: 'Гидролизуемая под действием ферментнов карбоксиметилцеллюлоза', namelat: 'Enzymically hydrolysed carboxymethylcellulose' },
  { number: 'E470', status: 'MUSHBOOH', namerus: 'Жирных кислотсоли калия, кальция, натрия', namelat: 'Sodium, potassium and calcium salts of fatty acids' },
  { number: 'E471', status: 'MUSHBOOH', namerus: 'Моно- и диглицериды жирных кислот ', namelat: 'Mono- and diglycerides of fatty acids' },
  { number: 'E472', status: 'MUSHBOOH', namerus: 'Различные эфиры моно- и диглицеридов жирных кислот', namelat: 'Various esters of mono- and diglycerides of fatty acids' },
  { number: 'E472E', status: 'MUSHBOOH', namerus: 'Эфиры глицерина, диацетилвинной и жирных кислот ', namelat: 'Mono- and diacetyl tartaric acid esters of mono- and diglycerides of fatty acids' },
  { number: 'E473', status: 'MUSHBOOH', namerus: 'Эфиры сахарозы и жирных кислот ', namelat: 'Sucrose esters of fatty acids' },
  { number: 'E474', status: 'MUSHBOOH', namerus: ' Сахароглицериды ', namelat: 'Sucroglycerides' },
  { number: 'E475', status: 'MUSHBOOH', namerus: 'Эфиры полиглицеридов и жирных кислот', namelat: 'Polyglycerol esters of fatty acids' },
  { number: 'E476', status: 'MUSHBOOH', namerus: 'Полиглицерин, полирицинолеаты', namelat: 'Polyglycerol polyricinoleate' },
  { number: 'E477', status: 'MUSHBOOH', namerus: 'Пропан-1,2-диоловые эфиры жирных кислот', namelat: 'Propane-1,2-diol esters of fatty acids, propylene glycol esters of fatty acids' },
  { number: 'E478', status: 'MUSHBOOH', namerus: 'Эфиры лактилированных жирных кислот глицерина и пропиленгликоля', namelat: 'Lactylated fatty acid esters of glycerol and propane-1' },
  { number: 'E479B', status: 'MUSHBOOH', namerus: 'Термически окисленное соевое и бобовое масло с моно- и диглицеридами жирных кислот', namelat: 'Thermally oxidized soya bean oil interacted with mono- and diglycerides of fatty acids' },
  { number: 'E481', status: 'MUSHBOOH', namerus: 'Стеароил-2-лактилат натрия', namelat: 'Sodium stearoyl-2-lactylate' },
  { number: 'E482', status: 'MUSHBOOH', namerus: 'Стеароил-2-лактилат кальция', namelat: 'Calcium stearoyl-2-lactylate' },
  { number: 'E483', status: 'MUSHBOOH', namerus: 'Стеарилтартрат', namelat: 'Stearyl tartrate' },
  { number: 'E491', status: 'MUSHBOOH', namerus: 'Сорбитан моностеарат', namelat: 'Sorbitan monostearate' },
  { number: 'E492', status: 'MUSHBOOH', namerus: 'Сорбитан тристеарат', namelat: 'Sorbitan tristearate' },
  { number: 'E493', status: 'MUSHBOOH', namerus: 'Сорбитан монолаурат', namelat: 'Sorbitan monolaurate' },
  { number: 'E494', status: 'MUSHBOOH', namerus: 'Сорбитан моноолеат', namelat: 'Sorbitan monooleate' },
  { number: 'E495', status: 'MUSHBOOH', namerus: 'Сорбитан монопальмитат', namelat: 'Sorbitan monopalmitate' },
  { number: 'E500', status: 'HALAL', namerus: 'Карбонат натрия', namelat: 'Sodium carbonate/sodium' },
  { number: 'E501', status: 'HALAL', namerus: 'Карбонат калия', namelat: 'Potassium carbonate/potassium' },
  { number: 'E503', status: 'HALAL', namerus: 'Карбонат аммония', namelat: 'Ammonium carbonate' },
  { number: 'E504', status: 'HALAL', namerus: 'Карбонат магния ', namelat: 'Magnesium carbonate' },
  { number: 'E507', status: 'HALAL', namerus: 'Соляная кислота', namelat: 'Hydrochloric acid' },
  { number: 'E508', status: 'HALAL', namerus: 'Хлорид калия', namelat: 'Potassium chloride' },
  { number: 'E509', status: 'HALAL', namerus: 'Хлорид кальция ', namelat: 'Calcium chloride' },
  { number: 'E510', status: 'HALAL', namerus: 'Хлорид аммония ', namelat: 'Ammonium chloride' },
  { number: 'E511', status: 'HALAL', namerus: 'Хлорид магния', namelat: 'Magnesium chloride' },
  { number: 'E512', status: 'HALAL', namerus: 'Хлорид олова', namelat: 'Stannous chloride' },
  { number: 'E513', status: 'HALAL', namerus: 'Серная кислота', namelat: 'Sulphuric acid' },
  { number: 'E514', status: 'HALAL', namerus: 'Сульфат натрия', namelat: 'Sodium sulphate' },
  { number: 'E515', status: 'HALAL', namerus: 'Сульфат калия ', namelat: ' Potassium sulphate' },
  { number: 'E516', status: 'HALAL', namerus: 'Сульфат кальция', namelat: ' Calcium sulphate' },
  { number: 'E517 ', status: 'HALAL', namerus: 'Сульфат аммония', namelat: 'Ammonium sulphate' },
  { number: 'E518', status: 'HALAL', namerus: 'Сульфат магния ', namelat: 'Magnesium sulphate' },
  { number: 'E520', status: 'HALAL', namerus: 'Сульфат алюминия ', namelat: ' Aluminium sulphate' },
  { number: 'E521', status: 'HALAL', namerus: 'Сульфат алюминия-натрия', namelat: 'Aluminium sodium sulphate' },
  { number: 'E522', status: 'HALAL', namerus: 'Сульфат алюминия-калия', namelat: 'Aluminium potassium sulphate' },
  { number: 'E523', status: 'HALAL', namerus: 'Сульфат алюминия-аммония ', namelat: 'Aluminium ammonium sulphate' },
  { number: 'E524', status: 'HALAL', namerus: 'Гидроксид натрия', namelat: 'Sodium hydroxide' },
  { number: 'E525', status: 'HALAL', namerus: 'Гидроксид калия ', namelat: ' Potassium hydroxide' },
  { number: 'E526', status: 'HALAL', namerus: 'Гидроксид кальция', namelat: 'Calcium hydroxide' },
  { number: 'E527', status: 'HALAL', namerus: 'Гидроксид аммония', namelat: ' Ammonium hydroxide' },
  { number: 'E528', status: 'HALAL', namerus: 'Гидроксид магния ', namelat: 'Magnesium hydroxide' },
  { number: 'E529', status: 'HALAL', namerus: 'Оксид кальция', namelat: 'Calcium oxide' },
  { number: 'E530', status: 'HALAL', namerus: 'Оксид магния ', namelat: 'Magnesium oxide' },
  { number: 'E535', status: 'HALAL', namerus: 'Ферроцианид натрия ', namelat: 'Sodium ferrocyanide' },
  { number: 'E536', status: 'HALAL', namerus: 'Ферроцианид калия ', namelat: ' Potassium ferrocyanide' },
  { number: 'E538', status: 'HALAL', namerus: 'Ферроцианид кальция', namelat: 'Calcium ferrocyanide' },
  { number: 'E540', status: 'HALAL', namerus: 'Дикальция дифосфат ', namelat: 'Dicalcium diphosphate' },
  { number: 'E541', status: 'HALAL', namerus: 'Алюмофосфат натрия', namelat: 'Sodium aluminium phosphate' },
  { number: 'E542', status: 'MUSHBOOH', namerus: 'Костный фосфат ', namelat: ' Edible bone phosphate (bone-meal)' },
  { number: 'E544', status: 'HALAL', namerus: 'Полифосфат кальция', namelat: 'Calcium polyphosphate' },
  { number: 'E545', status: 'HALAL', namerus: 'Полифосфат аммония ', namelat: ' Ammonium polyphosphate' },
  { number: 'E550', status: 'HALAL', namerus: 'Силикат натрия', namelat: 'Sodium Silicate' },
  { number: 'E551', status: 'HALAL', namerus: 'Диоксид кремния ', namelat: 'Silicon dioxide (Silica salt)' },
  { number: 'E552', status: 'HALAL', namerus: 'Силикат кальция', namelat: 'Calcium silicate' },
  { number: 'E553', status: 'HALAL', namerus: 'Силикат магния/тальк', namelat: 'Magnesium silicate/ Magnesium trisilicate (talc)' },
  { number: 'E554', status: 'HALAL', namerus: 'Алюмосиликат натрия ', namelat: 'sodium aluminium silicate' },
  { number: 'E555', status: 'HALAL', namerus: 'Алюмосиликат калия', namelat: 'Potassium aluminium silicate' },
  { number: 'E556', status: 'HALAL', namerus: 'Алюмосиликат кальция ', namelat: 'calcium aluminium silicate' },
  { number: 'E558', status: 'HALAL', namerus: 'Бентонит', namelat: 'Bentonite' },
  { number: 'E559', status: 'HALAL', namerus: 'Алюмосиликат (Каолин)', namelat: 'Aluminium silicate (Kaolin)' },
  { number: 'E570', status: 'MUSHBOOH', namerus: 'Стеариновая кислота', namelat: 'Stearic acid' },
  { number: 'E572', status: 'MUSHBOOH', namerus: 'Стеарат магния ', namelat: 'Magnesium stearate' },
  { number: 'E574', status: 'HALAL', namerus: 'Глюконовая кислота ', namelat: 'Gluconic acid' },
  { number: 'E575', status: 'HALAL', namerus: 'Глюконо-дельта-лактон', namelat: 'Glucono delta-lactone' },
  { number: 'E576', status: 'HALAL', namerus: 'Глюконат натрия', namelat: 'Sodium gluconate' },
  { number: 'E577', status: 'HALAL', namerus: 'Глюконат калия', namelat: 'Potassium gluconate' },
  { number: 'E578', status: 'HALAL', namerus: 'Глюконат кальция', namelat: 'Calcium gluconate' },
  { number: 'E585', status: 'HALAL', namerus: 'Лактат железа', namelat: 'Ferrous lactate' },
  { number: 'E620', status: 'HALAL', namerus: 'Глутаминовая кислота', namelat: 'Glutamic acid' },
  { number: 'E621', status: 'HALAL', namerus: 'Глютамат натрия', namelat: 'Monosodium glutamate' },
  { number: 'E622', status: 'HALAL', namerus: 'Глутамат калия однозамещенный', namelat: 'Monopotassium glutamate' },
  { number: 'E623', status: 'HALAL', namerus: 'Диглутамат кальция', namelat: 'Calcium diglutamate' },
  { number: 'E624', status: 'HALAL', namerus: 'Глутамат аммония однозамещенный', namelat: 'Monoammonium glutamate' },
  { number: 'E625', status: 'HALAL', namerus: 'Диглутамат магния', namelat: 'Magnesium diglutamate' },
  { number: 'E626', status: 'HALAL', namerus: 'Гуаниловая кислота', namelat: 'Guanylic acid' },
  { number: 'E627', status: 'HALAL', namerus: 'Гуанилат натрия', namelat: 'sodium guanylate' },
  { number: 'E628', status: 'HALAL', namerus: '5-гуанилат калия двузамещенный', namelat: ' Dipotassium guanylate' },
  { number: 'E629', status: 'HALAL', namerus: '5-гуанилат кальция', namelat: 'Calcium guanylate' },
  { number: 'E630', status: 'MUSHBOOH', namerus: 'Инозиновая кислота', namelat: 'Inosinic acid' },
  { number: 'E631', status: 'MUSHBOOH', namerus: 'Инозинат натрия двузамещенный', namelat: 'Disodium inosinate' },
  { number: 'E632', status: 'MUSHBOOH', namerus: 'Инозинат калия двузамещенный', namelat: 'Dipotassium inosinate' },
  { number: 'E633', status: 'MUSHBOOH', namerus: '5-инозинат кальция', namelat: 'Calcium inosinate ' },
  { number: 'E634', status: 'MUSHBOOH', namerus: '5-рибонуклеотиды кальция', namelat: 'Calcium 5 &#039;-ribonucleotides' },
  { number: 'E635', status: 'MUSHBOOH', namerus: '5-рибонуклеотиды натрия двузамещенные', namelat: 'Disodium 5 &#039;-ribonucleotides' },
  { number: 'E636', status: 'HALAL', namerus: 'Мальтол', namelat: 'Maltol' },
  { number: 'E637', status: 'HALAL', namerus: 'Этилмальтол', namelat: 'Ethyl maltol' },
  { number: 'E640', status: 'MUSHBOOH', namerus: 'Глицин и его натриевые соли', namelat: 'Glycine and its sodium salt' },
  { number: 'E650', status: 'HALAL', namerus: 'Ацетат цинка', namelat: 'Zinc acetate' },
  { number: 'E900', status: 'HALAL', namerus: 'Диметилполисилоксан', namelat: 'Dimethyl polysiloxane' },
  { number: 'E901', status: 'HALAL', namerus: 'Пчелиный воск', namelat: 'Beeswax' },
  { number: 'E902', status: 'HALAL', namerus: 'Воск карнаубский', namelat: 'Candelilla wax' },
  { number: 'E903', status: 'HALAL', namerus: 'Воск свечной', namelat: 'Carnauba wax' },
  { number: 'E904', status: 'MUSHBOOH', namerus: 'Шеллак', namelat: 'Shellac' },
  { number: 'E905', status: 'HALAL', namerus: 'Парафины', namelat: 'Paraffins' },
  { number: 'E907', status: 'HALAL', namerus: 'Поли-1-децен гидрогенизированный', namelat: 'Refined microcrystalline wax' },
  { number: 'E912', status: 'HALAL', namerus: 'Эфиры монтаниновой кислоты', namelat: 'Montanic acid esters' },
  { number: 'E913', status: 'HALAL', namerus: 'Ланолин', namelat: 'Lanolin' },
  { number: 'E914', status: 'HALAL', namerus: 'Окисленный полиэтиленовый воск', namelat: 'Oxidized polyethylene wax' },
  { number: 'E920', status: 'MUSHBOOH', namerus: 'L-цистеин', namelat: 'L-cysteine hydrochloride' },
  { number: 'E924', status: 'HALAL', namerus: 'Бромат калия', namelat: 'Potassium bromate' },
  { number: 'E925', status: 'HALAL', namerus: 'Хлор', namelat: 'Chlorine' },
  { number: 'E926', status: 'HALAL', namerus: 'Диоксид хлора', namelat: 'Chlorine dioxide' },
  { number: 'E927B', status: 'HALAL', namerus: 'Карбамид', namelat: 'Carbamide' },
  { number: 'E938', status: 'HALAL', namerus: 'Аргон', namelat: 'Argon' },
  { number: 'E939', status: 'HALAL', namerus: 'Гелий', namelat: 'Helium' },
  { number: 'E940', status: 'HALAL', namerus: 'Дихлордифторметан', namelat: 'Dichlorodifluoromethane' },
  { number: 'E941', status: 'HALAL', namerus: 'Азот', namelat: 'Nitrogen' },
  { number: 'E942', status: 'HALAL', namerus: 'Закись азота', namelat: 'Nitrous oxide' },
  { number: 'E943A', status: 'HALAL', namerus: 'Бутан', namelat: 'Butane' },
  { number: 'E943B', status: 'HALAL', namerus: 'Изобутан', namelat: 'Isobutane' },
  { number: 'E944', status: 'HALAL', namerus: 'Пропан', namelat: 'Propane' },
  { number: 'E949', status: 'HALAL', namerus: 'Водород', namelat: 'Hydrogen' },
  { number: 'E951', status: 'HALAL', namerus: 'Аспартам', namelat: 'Aspartame' },
  { number: 'E953', status: 'HALAL', namerus: 'Изомальтит', namelat: 'Isomalt' },
  { number: 'E954', status: 'HALAL', namerus: 'Сахарин', namelat: 'Saccharin' },
  { number: 'E965', status: 'HALAL', namerus: 'Мальтит', namelat: 'Sucralose' },
  { number: 'E966', status: 'HALAL', namerus: 'Лактит', namelat: 'Alitame' },
  { number: 'E967', status: 'HALAL', namerus: 'Тауматин', namelat: 'Thaumatin' },
  { number: 'E999', status: 'HARAM', namerus: 'Экстракт Квиллайи', namelat: 'Quillaia extract' },
  { number: '', status: 'HALAL', namerus: 'Уксусная кислота', namelat: 'Acetic acid' },
  { number: '', status: 'HALAL', namerus: 'Ацетон', namelat: 'Acetone' },
  { number: '', status: 'HARAM', namerus: 'Аденозин 5 &#039;-монофосфат', namelat: 'Adenosine 5- Monophosphate' },
  { number: '', status: 'HALAL', namerus: 'Агар', namelat: 'Agar' },
  { number: '', status: 'HALAL', namerus: 'Альбумин', namelat: 'Albumin' },
  { number: '', status: 'HARAM', namerus: 'Алкоголь как растворитель для придания аромата', namelat: 'Alcohol as solvent in flavour' },
  { number: '', status: 'HARAM', namerus: 'Алкоголь в сухой форме в качестве ингредиента', namelat: 'Alcohol in dry form used as ingredient' },
  { number: '', status: 'HALAL', namerus: 'Альгин', namelat: 'Algin' },
  { number: '', status: 'HALAL', namerus: 'Душистый перец', namelat: 'Allspice' },
  { number: '', status: 'HALAL', namerus: 'Квасцы', namelat: 'Alum' },
  { number: '', status: 'HALAL', namerus: 'Сульфат алюминия', namelat: 'Aluminum sulphate' },
  { number: '', status: 'HALAL', namerus: 'Аммоний (бикарбонат, карбонат, хлорид, сульфат)', namelat: 'Ammonium (bicarbonate, carbonate, chloride, sulfate)' },
  { number: '', status: 'HALAL', namerus: 'Альфа-амилаза', namelat: 'Amylase (Alpha)' },
  { number: '', status: 'HALAL', namerus: 'Анис', namelat: 'Anise' },
  { number: '', status: 'HALAL', namerus: 'Аннатто', namelat: 'Annatto' },
  { number: '', status: 'HALAL', namerus: 'Арроурут', namelat: 'Arrowroot' },
  { number: '', status: 'MUSHBOOH', namerus: 'Искусственные красители', namelat: 'Artificial colours' },
  { number: '', status: 'MUSHBOOH', namerus: 'Искусственные ароматизаторы', namelat: 'Artificial flavours' },
  { number: '', status: 'HALAL', namerus: 'Аскорбиновая кислота', namelat: 'Ascorbic acid' },
  { number: '', status: 'HALAL', namerus: 'Аскорбиновая кислота (Витамин С)', namelat: 'ascorbic acid or vitamin C' },
  { number: '', status: 'HALAL', namerus: 'Аспартам', namelat: 'Aspartame' },
  { number: '', status: 'HALAL', namerus: 'Азодикарбонамид', namelat: 'Azodicarbonamide' },
  { number: '', status: 'HARAM', namerus: 'Бекон', namelat: 'Bacon' },
  { number: '', status: 'HARAM', namerus: 'Кусочки бекона', namelat: 'Bacon bits' },
  { number: '', status: 'HALAL', namerus: 'Пекарские дрожжи', namelat: 'Bakers yeast' },
  { number: '', status: 'HALAL', namerus: 'Экстракт пекарских дрожжей', namelat: 'Bakers yeast extract' },
  { number: '', status: 'HALAL', namerus: 'Разрыхлитель теста', namelat: 'Baking powder' },
  { number: '', status: 'HALAL', namerus: 'Пищевая сода', namelat: 'Baking soda' },
  { number: '', status: 'HARAM', namerus: 'Бальзамический уксус', namelat: 'Balsamic vinegar' },
  { number: '', status: 'HALAL', namerus: 'Базилик', namelat: 'Basil' },
  { number: '', status: 'HALAL', namerus: 'Лавровый лист', namelat: 'Bay leaves' },
  { number: '', status: 'HARAM', namerus: 'Пиво', namelat: 'Beer' },
  { number: '', status: 'HARAM', namerus: 'Ароматизатор пива', namelat: 'Beer Flavour' },
  { number: '', status: 'HALAL', namerus: 'Пчелиный воск', namelat: 'Beeswax' },
  { number: '', status: 'HALAL', namerus: 'Бензальдегид', namelat: 'Benzaldehyde' },
  { number: '', status: 'HALAL', namerus: 'Бензойная кислота', namelat: 'Benzoic acid' },
  { number: '', status: 'MUSHBOOH', namerus: 'Бета-каротин', namelat: 'Beta-carotene' },
  { number: '', status: 'MUSHBOOH', namerus: 'Бутилоксианизол или бутилгидрокситолуол', namelat: 'Bha or Bht' },
  { number: '', status: 'HALAL', namerus: 'Отруби', namelat: 'Bran' },
  { number: '', status: 'HARAM', namerus: 'Экстракт пивных дрожжей', namelat: 'Brewers yeast extract' },
  { number: '', status: 'HARAM', namerus: 'Пивные дрожжи', namelat: 'Brewers yeast' },
  { number: '', status: 'HALAL', namerus: 'Булгур', namelat: 'Bulgur wheat' },
  { number: '', status: 'MUSHBOOH', namerus: 'Липолизированный молочный жир', namelat: 'Butter fat lipolyzed' },
  { number: '', status: 'MUSHBOOH', namerus: 'Сухие кисломолочные продукты', namelat: 'Buttermilk solids' },
  { number: '', status: 'HALAL', namerus: 'Кофеин', namelat: 'Caffeine' },
  { number: '', status: 'HALAL', namerus: 'Кальций (Карбонат, хлорид, цитрат, сорбат, сульфат)', namelat: 'Calcium (Carbonate, Chloride, Citrate, Sorbate, Sulfate)' },
  { number: '', status: 'HALAL', namerus: 'Пропионат кальция', namelat: 'Calcium propionate' },
  { number: '', status: 'MUSHBOOH', namerus: 'Стеарат кальция', namelat: 'Calcium Stearate' },
  { number: '', status: 'MUSHBOOH', namerus: 'Стеароил-лактилат кальция', namelat: 'Calcium Stearoyl Lactylate' },
  { number: '', status: 'HALAL', namerus: 'Масло канолы', namelat: 'Canola oil' },
  { number: '', status: 'HALAL', namerus: 'Карамель', namelat: 'Caramel' },
  { number: '', status: 'HALAL', namerus: 'Тмин', namelat: 'Caraway' },
  { number: '', status: 'HALAL', namerus: 'Карбоксиметилцеллюлоза', namelat: 'Carboxymethylcellulose' },
  { number: '', status: 'HALAL', namerus: 'Кардамон', namelat: 'Cardamom' },
  { number: '', status: 'HALAL', namerus: 'Воск карнаубский', namelat: 'Carnauba wax' },
  { number: '', status: 'HALAL', namerus: 'Рожковое дерево', namelat: 'Carob' },
]
